### ISSUE TITLE
Trying to install from my command prompt, I got this

### ISSUE THREAD

**Issue by edfolmi** [PaystackOSS/paystack-python#3]
C:\Users\Hp\larjapoll>pip install paystacksdk
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement paystacksdk (from versions: none)
ERROR: No matching distribution found for paystacksdk

C:\Users\Hp\larjapoll>

**Comment by damilola-paystack** [comment]
Hi @edfolmi it seems you are missing a dash character in the SDK name. It should be `paystack-sdk`. Kindly [check PyPI](https://pypi.org/project/paystack-sdk/#files) for further clarification.
<img width="745" alt="Screenshot 2022-09-27 at 10 17 45" src="https://user-images.githubusercontent.com/60398567/192487104-09a277b5-7793-4cd3-9d03-307fdc7289d3.png">

**Comment by edfolmi** [comment]
it works, I appreciate you
