### ISSUE TITLE
Status of this Library

### ISSUE THREAD

**Issue by Pythonian** [PaystackOSS/paystack-python#5]
Hello maintainer(s),

Please I would like to know if this library is fairly stable, given that there has been little to no update on here. Can it be used in a production environment?

I have a client project that will require a heavy usage of Paystack to develop a Wallet system, so I will like to know if this library or another is the supported Python library for Paystack.

And lastly, if this project is still good to go, is contribution welcome?

Thank you.

**Comment by Andrew-Paystack** [comment]
Hey @Pythonian ,

I'm Andrew from the Developer Relations team. 

Despite the little activity, the library is good to go and you can definitely contribute to it. 

We're happy to support you with any issues you may run into. 🙏

**Comment by Pythonian** [comment]
Hi @Andrew-Paystack Thank you, it's comforting to know that this library is still very much relevant.

I have joined the Payslack channel, so if I should run into any issue while using it, I'll reach out via here or Slack.

Best regards.
